AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eTRON workspace functions template

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Resources:
  WorkspaceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/
      Handler: workspaceHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites

      Events:
        CreateWorkspace:
          Type: Api 
          Properties:
            Path: /workspace
            Method: post

        UpdateWorkspace:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}
            Method: put

        GetWorkspace:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}
            Method: get
            
        DeleteWorkspace:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}
            Method: delete

        InviteUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/invites/create
            Method: post

        CancelInvite:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/invites/cancel/{email}
            Method: delete

        ViewSentInvites:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/invites
            Method: get

        AddUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users/add/{inviteId}
            Method: post

        UpdateUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users/update/{userId}
            Method: put

        RemoveUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users/remove/{userId}
            Method: delete

        GetUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users/{userId}
            Method: get

        GetAllUsers:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users
            Method: get

        CreateRole:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles/create
            Method: post

        DeleteRole:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles/remove/{roleId}
            Method: delete

        GetRoles:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles
            Method: get


