version = 0.1
[default.deploy.parameters]
stack_name = "etron-backend"
resolve_s3 = true
s3_prefix = "etron-backend"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
