AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eTRON backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Parameters:
  WorkspaceBucketName:
    Type: String
  AppConfigurationBucketName:
    Type: String
  AthenaDatabaseName:
    Type: String
    Default: etron_day_book_db
    

Resources:

  AthenaGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref AthenaDatabaseName

  AuditQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AuditQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600 # 14 days

  WorkspaceDomainFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./workspace/template.yaml
      Parameters:
        AppConfigurationBucketName: !Ref AppConfigurationBucketName
        WorkspaceBucketName: !Ref WorkspaceBucketName
        AuditQueueUrl: !Ref AuditQueue

  AuditDomainFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./audit/template.yaml
      Parameters:
        AppConfigurationBucketName: !Ref AppConfigurationBucketName
        WorkspaceBucketName: !Ref WorkspaceBucketName
        AuditQueueArn: !Ref AuditQueue
        
  UserDomainFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./user/template.yaml
      Parameters:
        AppConfigurationBucketName: !Ref AppConfigurationBucketName
        AuditQueueUrl: !Ref AuditQueue
        
  DayBookFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/day-book/template.yaml
      Parameters:
        AppConfigurationBucketName: !Ref AppConfigurationBucketName
        WorkspaceBucketName: !Ref WorkspaceBucketName
        AthenaDatabaseName: !Ref AthenaDatabaseName
        AuditQueueUrl: !Ref AuditQueue