AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eTRON backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Resources:
  HelloWorldFunctionTwo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: common/workspace/functions/
      Handler: hello.helloHandler
      Events:
        HelloWorldTwo:
          Type: Api 
          Properties:
            Path: /hello/two
            Method: get

  WorkspaceFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./common/workspace/template.yaml
  ModuleFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./common/modules/template.yaml
  UserFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./common/users/template.yaml

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
 #HelloWorldApi:
    #Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    #Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  #HelloWorldFunction:
    #Description: "Hello World Lambda Function ARN"
    #Value: !GetAtt HelloWorldFunction.Arn
  #HelloWorldFunctionIamRole:
    #Description: "Implicit IAM Role created for Hello World function"
    #Value: !GetAtt HelloWorldFunctionRole.Arn
