AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eTRON backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Parameters:
  WorkspaceBucketName:
    Type: String
  AthenaDatabaseName:
    Type: String
    Default: etron_day_book_db
    

Resources:

  PermissionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub etron-permissions-bucket-${AWS::AccountId}-${AWS::Region}

  AthenaGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref AthenaDatabaseName

  WorkspaceDomainFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./workspace/template.yaml
      Parameters:
        PermissionsBucketName: !Ref PermissionsBucket
        
  UserDomainFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./user/template.yaml
      Parameters:
        PermissionsBucketName: !Ref PermissionsBucket
        
  DayBookFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/day-book/template.yaml
      Parameters:
        PermissionsBucketName: !Ref PermissionsBucket
        WorkspaceBucketName: !Ref WorkspaceBucketName
        AthenaDatabaseName: !Ref AthenaDatabaseName