AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eTRON user-domain functions template

Parameters:
  AppConfigurationBucketName:
    Type: String
  AuditQueueUrl:
    Type: String
  UserPoolArn:
    Type: String

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        APP_CONFIGURATION_BUCKET: !Ref AppConfigurationBucketName
        AUDIT_QUEUE_URL: !Ref AuditQueueUrl
        USERPOOL_ARN: !Ref UserPoolArn

Resources:

  eTRONApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
            Identity:
              Header: Authorization
  
  # User Lambda 
  UserCoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/user-core
      Handler: userHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        UpdateUser:
          Type: Api 
          Properties:
            Path: /user/{userId}/workspace/{workspaceId}
            Method: put
            RestApiId: !Ref eTRONApi


  # Invite Lambda 
  UserInvitesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/user-invites
      Handler: inviteHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        GetInvites:
          Type: Api 
          Properties:
            Path: /user/invites
            Method: get
            RestApiId: !Ref eTRONApi