AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eTRON workspace-domain functions template

Parameters:
  AppConfigurationBucketName:
    Type: String
  WorkspaceBucketName:
    Type: String
  AthenaDatabaseName:
    Type: String
    Default: etron_day_book_db
  AuditQueueUrl:
    Type: String
  UserPoolArn:
    Type: String
    
Globals:
  Function:
    Timeout: 5
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        APP_CONFIGURATION_BUCKET: !Ref AppConfigurationBucketName
        WORKSPACE_BUCKET: !Ref WorkspaceBucketName
        ATHENA_DATABASE: !Ref AthenaDatabaseName
        AUDIT_QUEUE_URL: !Ref AuditQueueUrl
        USERPOOL_ARN: !Ref UserPoolArn

Resources:

  eTRONApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: dev
        Auth:
          DefaultAuthorizer: CognitoAuthorizer
          Authorizers:
            CognitoAuthorizer:
              UserPoolArn: !Ref UserPoolArn
              Identity:
                Header: Authorization

  # Workspace Lambda 
  WorkspaceCoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/workspace-core
      Handler: workspaceHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - DynamoDBCrudPolicy:
            TableName: AuditLogs
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        CreateWorkspace:
          Type: Api 
          Properties:
            Path: /workspace
            Method: post
            RestApiId: !Ref eTRONApi

        UpdateWorkspace:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}
            Method: patch
            RestApiId: !Ref eTRONApi

        GetWorkspace:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}
            Method: get
            RestApiId: !Ref eTRONApi

        GetWorkspaceByUserId:
          Type: Api 
          Properties: 
            Path: /workspace/users/{userId}
            Method: get
            RestApiId: !Ref eTRONApi

        TransferOwnership:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/transfer
            Method: put
            RestApiId: !Ref eTRONApi

        GetDefaultPermissions:
          Type: Api
          Properties:
            Path: /workspace/permissions 
            Method: get
            RestApiId: !Ref eTRONApi

  # Invite Lambda 
  WorkspaceInvitesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/workspace-invites
      Handler: inviteHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        InviteUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/invites
            Method: post
            RestApiId: !Ref eTRONApi

        CancelUsersInvites:
          Type: Api 
          Properties:
            Path: /workspace/invites
            Method: delete
            RestApiId: !Ref eTRONApi

        CancelInvite:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/invites/{inviteId}
            Method: delete
            RestApiId: !Ref eTRONApi
        
        GetInvite:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/invites/{inviteId}
            Method: get
            RestApiId: !Ref eTRONApi

        GetSentInvites:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/invites
            Method: get
            RestApiId: !Ref eTRONApi

  # User Lambda 
  WorkspaceUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/workspace-users
      Handler: userHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        AddUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users
            Method: post
            RestApiId: !Ref eTRONApi

        UpdateUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users/{userId}
            Method: patch
            RestApiId: !Ref eTRONApi

        RemoveUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users/{userId}
            Method: delete
            RestApiId: !Ref eTRONApi

        GetUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users/{userId}
            Method: get
            RestApiId: !Ref eTRONApi

        GetAllUsers:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/users
            Method: get
            RestApiId: !Ref eTRONApi
        

  # Role Lambda 
  WorkspaceRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/workspace-roles
      Handler: roleHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        CreateRole:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles
            Method: post
            RestApiId: !Ref eTRONApi

        UpdateRole:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles/{roleId}
            Method: patch
            RestApiId: !Ref eTRONApi

        DeleteRole:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles/{roleId}
            Method: delete
            RestApiId: !Ref eTRONApi

        GetRole:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles/{roleId}
            Method: get
            RestApiId: !Ref eTRONApi

        GetRoleOfUser:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roleOfUser
            Method: get
            RestApiId: !Ref eTRONApi

        GetRoles:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/roles
            Method: get
            RestApiId: !Ref eTRONApi


  # Board Lambda 
  WorkspaceBoardsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/workspace-boards
      Handler: boardHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        CreateBoard:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/boards
            Method: post
            RestApiId: !Ref eTRONApi

        UpdateBoard:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/boards/{boardId}
            Method: patch
            RestApiId: !Ref eTRONApi

        DeleteBoard:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/boards/{boardId}
            Method: delete
            RestApiId: !Ref eTRONApi

        GetBoard:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/boards/{boardId}
            Method: get
            RestApiId: !Ref eTRONApi

        GetBoards:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/boards
            Method: get
            RestApiId: !Ref eTRONApi

  # Workspace Deletion Lambda 
  WorkspaceRemovalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/workspace-remover
      Handler: removerHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - DynamoDBCrudPolicy:
            TableName: DataSources
        - DynamoDBCrudPolicy:
            TableName: Metrics
        - DynamoDBCrudPolicy:
            TableName: Reports
        - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
              - s3:HeadObject
            Resource: "*"
          - Effect: Allow
            Action:
              - athena:StartQueryExecution
              - athena:GetQueryExecution
              - athena:GetQueryResults
              - athena:GetWorkGroup
            Resource: "*"
          - Effect: Allow
            Action:
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetTables
              - glue:CreateTable
              - glue:UpdateTable
              - glue:DeleteTable
            Resource:
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        DeleteWorkspace:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}
            Method: delete
            RestApiId: !Ref eTRONApi

  # Module Lambda 
  WorkspaceModulesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/workspace-modules
      Handler: moduleHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Workspaces
        - DynamoDBCrudPolicy:
            TableName: WorkspaceUsers
        - DynamoDBCrudPolicy:
            TableName: WorkspaceInvites
        - DynamoDBCrudPolicy:
            TableName: DataSources
        - DynamoDBCrudPolicy:
            TableName: Metrics
        - DynamoDBCrudPolicy:
            TableName: Reports
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
              - s3:HeadObject
            Resource: "*"
          - Effect: Allow
            Action:
              - athena:StartQueryExecution
              - athena:GetQueryExecution
              - athena:GetQueryResults
              - athena:GetWorkGroup
            Resource: "*"
          - Effect: Allow
            Action:
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetTables
              - glue:CreateTable
              - glue:UpdateTable
              - glue:DeleteTable
            Resource:
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminUpdateUserAttributes
            Resource:
              - !Ref UserPoolArn

      Events:
        InstallModule:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/modules/{moduleKey}
            Method: post
            RestApiId: !Ref eTRONApi

        ToggleModule:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/modules/{moduleKey}/toggle
            Method: put
            RestApiId: !Ref eTRONApi

        UninstallModule:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/modules/{moduleKey}
            Method: delete
            RestApiId: !Ref eTRONApi

        GetInstalledModules:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/modules/installed
            Method: get
            RestApiId: !Ref eTRONApi

        GetUninstalledModules:
          Type: Api 
          Properties:
            Path: /workspace/{workspaceId}/modules/uninstalled
            Method: get
            RestApiId: !Ref eTRONApi