name: Backend CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
          
  backend_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend to AWS
    #needs: backend_test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up the AWS credentials for Develop
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID_DEV }}
          aws-region: ap-southeast-2

      - name: Set up the AWS credentials for Main/Prod
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID_PROD }}
          aws-region: ap-southeast-2

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies for deployment
        run: |
          cd backend
          npm install

      - name: Build the SAM app
        run: |
          cd backend
          sam build --no-cached

      - name: Set the stack name for develop
        if: github.ref == 'refs/heads/develop'
        run: echo "STACK_NAME=etron-dev" >> $GITHUB_ENV

      - name: Set the stack name for prod
        if: github.ref == 'refs/heads/main'
        run: echo "STACK_NAME=etron-prod" >> $GITHUB_ENV

      - name: Check STACK_NAME
        run: echo "STACK_NAME=${{ env.STACK_NAME }}"
