name: Backend CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
