name: Backend CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:

  backend_build:
    runs-on: ubuntu-latest
    name: Backend Build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js for building
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies for building
        run: |
          cd backend
          npm install

      - name: Build the SAM application
        run: |
          cd backend
          sam build --no-cached
  
  backend_test:
    runs-on: ubuntu-latest
    name: Backend Tests
    needs: backend_build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js for testing
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies for testing
        run: |
          cd backend
          npm install

      - name: Run test for the SAM application
        run: |
          cd backend
          npm run test
          
  backend_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend to AWS
    needs: backend_test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up the AWS credentials for Develop
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID_DEV }}
          aws-region: ap-southeast-2

      - name: Set up the AWS credentials for Main/Prod
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID_PROD }}
          aws-region: ap-southeast-2

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies for deployment
        run: |
          cd backend
          npm install

      - name: Build the SAM app
        run: |
          cd backend
          sam build --no-cached

      - name: Set the stack name
        id: set_stack_name
        run: |
          if [[ github.ref == 'refs/heads/develop' ]]; then
            echo "STACK_NAME = etron-dev" >> $GITHUB_ENV
          elif [[ github.ref == 'refs/heads/main' ]]; then
            echo "STACK_NAME = etron-prod" >> $GITHUB_ENV
          fi
        
      - name: Deploy the SAM app
        run: |
          cd backend
          sam deploy --stack-name "${{ env.STACK_NAME }}" \
                      --region ap-southeast-2 \
                      --capabilities CAPABILITY_IAM \
                      --confirm-changeset \
                      --no-disable-rollback
