name: Backend CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
      - 'feature-*'
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - main
      - develop
      - 'feature-*'
    paths:
      - 'backend/**'

jobs:
  backend_build:
    runs-on: ubuntu-latest
    name: Backend Build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js for building
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Python for build preparation
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Prepare shared packages and clean installs
        run: |
          cd backend
          python3 prep.py

      - name: Pack and copy shared packages
        run: |
          mkdir -p backend/.aws-sam/shared
          mkdir -p backend/.aws-sam/audit/audit-shared
          pushd shared
          npm pack
          mv *.tgz ../backend/.aws-sam/shared/
          popd
          pushd audit/audit-shared
          npm pack
          mv *.tgz ../../backend/.aws-sam/audit/audit-shared/
          popd


      - name: Cache SAM build artifacts
        uses: actions/cache@v4
        with:
          path: backend/.aws-sam
          key: ${{ runner.os }}-sam-${{ github.sha }}

      - name: Build the SAM application
        run: ls -R backend/.aws-sam || true
        run: |
          cd backend
          sam build --no-cached
  
  backend_test:
    runs-on: ubuntu-latest
    name: Backend Tests
    needs: backend_build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Restore cached SAM build artifacts
        uses: actions/cache@v4
        with:
          path: backend/.aws-sam
          key: ${{ runner.os }}-sam-${{ github.sha }}

      - name: Set up Node.js for testing
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies for testing
        run: |
          cd backend
          npm install

      - name: Run test for the SAM application
        run: |
          cd backend
          npm run test       
  backend_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend to AWS
    needs: backend_test
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up the AWS credentials for Develop
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID_DEV }}
          aws-region: ap-southeast-2

      - name: Set up the AWS credentials for Main/Prod
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID_PROD }}
          aws-region: ap-southeast-2

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Python for build preparation
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Prepare shared packages and clean installs
        run: |
          cd backend
          python3 scripts/prepare_build.py

      - name: Build the SAM app
        run: |
          cd backend
          sam build --no-cached

      - name: Set the stack name for develop
        if: github.ref == 'refs/heads/develop'
        run: echo "STACK_NAME=etron-dev" >> $GITHUB_ENV

      - name: Set the stack name for prod
        if: github.ref == 'refs/heads/main'
        run: echo "STACK_NAME=etron-prod" >> $GITHUB_ENV

      - name: Deploy the SAM app
        run: |
          cd backend
          sam deploy --stack-name "${{ env.STACK_NAME }}" \
                      --region ap-southeast-2 \
                      --capabilities CAPABILITY_IAM \
                      --no-confirm-changeset \
                      --no-disable-rollback
