name: Frontend CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
      - 'feature-*'
    paths:
      - 'frontend/**'

  pull_request:
    branches:
      - main
      - develop
      - 'feature-*'
    paths:
      - 'frontend/**'
