name: Frontend CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
      - 'feature-*'
    paths:
      - 'frontend/**'

  pull_request:
    branches:
      - main
      - develop
      - 'feature-*'
    paths:
      - 'frontend/**'


jobs:
  frontend_test:
    runs-on: ubuntu-latest
    name: Run tests for React Native App

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
         
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run Unit and Integration tests
        run: |
          cd frontend
          npm run test


  #frontend_deploy_build:
    #runs-on: ubuntu-latest
    #name: Deploy to Expo and build for iOS and Android
    #needs: frontend_test
    #if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
